name = "SequentialPointProcesses"
uuid = "010c2e22-af7e-49a1-ac5c-048ce8d3937f"
authors = ["Mikko Kuronen"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
